config/routes.rb
Rails.application.routes.draw do
  
  # Semi-static page routes
  get 'home', to: 'home#index', as: :index
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search
  get 'home/filter', to: 'home#filter', as: :filter
  root 'home#index'


  # Authentication and users
  resources :sessions
  resources :users
  get 're_entrants/new', to: 're_entrants#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

 # Special routes
  get 'resources/:id/share/', to: 'transactions#new', as: :share_resource_path
  get 'resources/:id/confirm', to: 'transactions#confirm', as: :confirm_resource_path
  get 'resources/:id/use_resource', to: 'transactions#use_resource', as: :use_resource_path
  get 'resources/:id/deactivate_resource', to: 'resources#deactivate', as: :deactivate_resource_path
  get 'resources/:id/reactivate_resource', to: 'resources#reactivate', as: :reactivate_resource_path
  get 're_entrants/:id/deactivate', to: 're_entrants#deactivate', as: :deactivate_reentrant_path
  get 're_entrants/:id/reactivate', to: 're_entrants#reactivate', as: :reactivate_reentrant_path
  get 'outreach_workers/:id/deactivate', to: 'outreach_workers#deactivate', as: :deactivate_sow_path
  get 'outreach_workers/:id/reactivate', to: 'outreach_workers#reactivate', as: :reactivate_sow_path

  # Additional Quality-of-life routes
  get 'user/referrals', to: 'users#referrals', as: :get_referral_path
  get 're_entrants/referrals', to: 're_entrants#referrals', as: :get_reentrant_referral_path

  get 'outreach_workers/referred_users', to: 'outreach_workers#referred', as: :get_referred_users_path
  get 'outreach_workers/referrals', to: 'outreach_workers#referrals', as: :get_sow_referral_path


  # Default routes
  resources :outreach_workers
  resources :re_entrants
  resources :flags
  resources :resources
  resources :tags
  resources :transactions

  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/re_entrant.rb
class ReEntrant < ApplicationRecord


  belongs_to :user
  has_many :transactions
  has_many :outreach_workers, through: :transactions
  # delegates
  delegate :email, to: :user, allow_nil: true
  delegate :phone, to: :user, allow_nil: true
  delegate :first_name, to: :user, allow_nil: true
  delegate :last_name, to: :user, allow_nil: true
  # Scopes
  scope :for_sow, ->(sow_id) { joins(:transactions).where('outreach_worker.id = ?', sow_id).distinct }
  scope :alphabetical, -> {includes(:user).order('users.first_name, users.last_name')}
  scope :for_neighborhood, -> (area) { where('neighborhood = ?', area)}
  scope :active,       -> { where(active: true) }
  
  def full_name
    user.first_name + " " + user.last_name
  end




end

app/controllers/re_entrants_controller.rb
class ReEntrantsController < ApplicationController
  before_action :set_re_entrant, only: [:show, :edit, :update, :destroy, :deactivate, :reactivate]

  # GET /re_entrants
  # GET /re_entrants.json
  def index
    if params[:re_entrant]
      @re_entrants = ReEntrant.for_neighborhood(params[:re_entrant][:for_neighborhood]).paginate(:page => params[:page]).per_page(10)
    else
      @re_entrants = ReEntrant.all.paginate(:page => params[:page]).per_page(10)
    end
  end

  # GET /re_entrants/1
  # GET /re_entrants/1.json
  def show
    @transactions = @re_entrant.transactions.paginate(:page => params[:page]).per_page(10)
  end

  # GET /re_entrants/new
  def new
    @re_entrant = ReEntrant.new
  end

  # GET /re_entrants/1/edit
  def edit
  end

  # POST /re_entrants
  # POST /re_entrants.json
  def create
    @user = User.new(user_params)
    @user.role = "reentrant"
    @re_entrant = ReEntrant.new
    @re_entrant.neighborhood = params[:re_entrant][:neighborhood]
    

    respond_to do |format|
      if @user.save
        @re_entrant.user_id = @user.id
        if @re_entrant.save
          session[:user_id] = @re_entrant.user.id
          logger.info("Saving is good!")
          format.html { redirect_to @re_entrant, notice: 'Your account was successfully created!' }
          format.json { render :show, status: :created, location: @re_entrant }
        else
          render action: 'new'
        end
      else
        # @user.valid?
        format.html { render :new, notice: 'Unable to save user' }
        format.json { render json: @re_entrant.errors, status: :unprocessable_entity }
        # render action: 'new'
      end
    end
  end

  # PATCH/PUT /re_entrants/1
  # PATCH/PUT /re_entrants/1.json
  def update
    respond_to do |format|
      if @re_entrant.update(re_entrant_params)
        format.html { redirect_to @re_entrant, notice: 'Re entrant was successfully updated.' }
        format.json { render :show, status: :ok, location: @re_entrant }
      else
        format.html { render :edit }
        format.json { render json: @re_entrant.errors, status: :unprocessable_entity }
      end
    end
  end

  def referrals
    @current = Transaction.for_re_entrant(current_user.reentrant.id).where("resource_accessed = ?", false).by_recent.paginate(:page => params[:page]).per_page(10)
    @past = Transaction.for_re_entrant(current_user.reentrant.id).where("resource_accessed = ?", true).by_recent.paginate(:page => params[:page]).per_page(10)
  end

  # DELETE /re_entrants/1
  # DELETE /re_entrants/1.json
  def destroy
    @re_entrant.destroy
    respond_to do |format|
      format.html { redirect_to re_entrants_url, notice: 'Re entrant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def deactivate
    respond_to do |format|
      @re_entrant.update(active: false)
      format.html { redirect_to re_entrants_url, notice: 'ReEntrant was successfully deactivated.' }
      format.json { head :no_content }
    end

  end

  def reactivate
    respond_to do |format|
      @re_entrant.update(active: true)
      format.html { redirect_to @re_entrant, notice: 'ReEntrant was successfully reactivated.' }
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_re_entrant
      @re_entrant = ReEntrant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def re_entrant_params
      params.require(:re_entrant).permit(:first_name, :last_name, :active, :email, :phone, :username, :password, :password_confirmation, :neighborhood, :user_id, :for_neighborhood)
    end

    def user_params
      params.require(:re_entrant).permit(:first_name, :last_name, :active, :email, :phone, :username, :password, :password_confirmation)
    end
end

app/helpers/re_entrants_helper.rb
module ReEntrantsHelper
end

app/views/re_entrants/_filter_reentrants.html.erb
<div id="filter">
  <%= form_tag(re_entrants_path, method: :get) do %>
    <%= collection_select :re_entrant, :for_neighborhood, ReEntrant.all, :neighborhood, :neighborhood, prompt: true %>
    <%= submit_tag("Filter") %>
  <% end %>
</div>

app/views/re_entrants/_form.html.erb
<%= form_with(model: re_entrant, local: true) do |form| %>
  <% if re_entrant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(re_entrant.errors.count, "error") %> prohibited this re_entrant from being saved:</h2>

      <ul>
      <% re_entrant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation  %>
    <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :neighborhood %>
    <%= form.text_field :neighborhood, class: "form-control" %>
  </div>

  

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  

  

  <div class="actions">
    <%= form.submit "Sign Up", class: "btn btn-primary btn-raised btn-lg" %>
  </div>
<% end %>

app/views/re_entrants/_re_entrant_fields.html.erb
 <%= f.input :neighborhood, label_html: { class: 'active' }, include: true%> 
 

app/views/re_entrants/_reentrant_fields.html.erb
 <%= f.input :neighborhood, label_html: { class: 'active' }, include: true%> 
 

app/views/re_entrants/_user_fields.html.erb
<%= f.input :email, label_html: { class: 'active' } %>
<%= f.input :phone, label_html: { class: 'active' } %>
<%= f.input :password, label_html: { class: 'active' } %>
<%= f.input :password_confirmation, label_html: { class: 'active' } %>
<%= f.input :first_name, label_html: { class: 'active' } %>
<%= f.input :last_name, label_html: { class: 'active' } %>

app/views/re_entrants/edit.html.erb
<div class="container">

<h2>Editing User</h2>

<%= render 'form', re_entrant: @re_entrant %>

<%= link_to 'Show', @re_entrant %> |
<%= link_to 'Back', re_entrants_path %>

</div>

app/views/re_entrants/index.html.erb
<div class = "container">

<p id="notice"><%= notice %></p>

<h1>Users</h1>

<%= render 'filter_reentrants' %>
<% if current_user.role?(:admin) %>
  <%= link_to 'New Re Entrant', new_re_entrant_path %>
<% end %>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Neighborhood</th>
      <th>Phone</th>
      <th>Email</th>
      <% if current_user.role?(:admin) %>
      <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @re_entrants.each do |re_entrant| %>
      <tr>

        <td><%= link_to re_entrant.user.name, re_entrant_path(re_entrant) %></td>
        <td><%= re_entrant.neighborhood %></td>
        <td><%= re_entrant.user.phone %></td>
        <td><%= re_entrant.email %></td>
        <% if current_user.role?(:admin) %>
        <td><%= link_to 'Edit', edit_re_entrant_path(re_entrant) %></td>
        <td><%= link_to 'Delete', re_entrant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



</div>

app/views/re_entrants/new.html.erb
<div class="container">

	<!-- <p id="notice"><%= notice %></p> -->


<h3>Create an Account</h3>

<p>Sign up to view our resource pool of employment, educational, job training resources, and more.

<%= render 'form', re_entrant: @re_entrant %>

</div>

app/views/re_entrants/referrals.html.erb
<div class="container">

<h2>My Referrals</h2>

<h3> Active Referrals </h3>
<% if @current.empty? %>
    <h4> You have no current referrals at this time </h4>
<% else %>
  <% @current.each do |referral| %>
    <div class="card" style="width: 20rem;">
      <div class="card-body">
        <h4 class="card-title"><%=link_to referral.resource.name, resource_path(referral.resource)%></h4>
        <h6 class="card-subtitle mb-2 text-muted">Referred by <%= link_to referral.outreach_worker.user.name, outreach_worker_path(referral.outreach_worker) %></h6>
        <p class="card-text"><%= truncate(referral.resource.desc, :length => 150, :separator => ' ') %>  </p>
        <% if current_user.role?(:reentrant) %>
          <a href="<%= referral.resource.webpage %>" class="card-link">Visit Website</a>
          <a href="<%=resource_path(referral.resource)%>" class="card-link">View Resource</a>
        <% else %>
          <a href="<%=resource_path(referral.resource)%>" class="card-link">View Resource</a>
          <a href="<%=share_resource_path_url(referral.resource)%>" class="card-link">Share</a>

        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

<br>

<h3> Used Referrals </h3>
<% if @past.empty? %>
    <h4> You have no past referrals at this time </h4>
<% else %>
  <% @past.each do |referral| %>
    <div class="card" style="width: 20rem;">
      <div class="card-body">
        <h4 class="card-title"><%=link_to referral.resource.name, resource_path(referral.resource)%></h4>
        <h6 class="card-subtitle mb-2 text-muted">Referred by <%= link_to referral.outreach_worker.user.name, outreach_worker_path(referral.outreach_worker) %></h6>
        <p class="card-text"><%=h truncate(referral.resource.desc, :length => 150) %> </p>
        <% if current_user.role?(:reentrant) %>
          <a href="<%= referral.resource.webpage %>" class="card-link">Visit Website</a>
          <a href="<%=resource_path(referral.resource)%>" class="card-link">View Resource</a>
        <% else %>
          <a href="<%=resource_path(referral.resource)%>" class="card-link">View Resource</a>
          <a href="<%=share_resource_path_url(referral.resource)%>" class="card-link">Share</a>

        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

</div>

app/views/re_entrants/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>
<h2><%= @re_entrant.user.name %></h2>

<% if not @re_entrant.active %>
  <p>This user is inactive</p>
  <% end %>

<hr>

<h4>Account Information</h4>

<p>
  <strong>Email:</strong>
  <%= @re_entrant.email %>
</p>
<p>
  <strong>Phone Number:</strong>
  <%= @re_entrant.phone %>
</p>
<p>
  <strong>Neighborhood:</strong>
  <%= @re_entrant.neighborhood %>
</p>

<% if @re_entrant.user == current_user %> 
<%= link_to 'Edit Your Account', edit_re_entrant_path(@re_entrant) %> 
<% end %>

<%if current_user.role?(:admin) %>
    <% if @re_entrant.active %>
      <%= link_to(deactivate_reentrant_path_url, class: 'btn btn-primary btn-raised btn-lg') do %>
        &nbsp;<%= "Deactivate ReEntrant" %>
      <% end %>
     <% else %>
       <%= link_to(reactivate_reentrant_path_url, class: 'btn btn-primary btn-raised btn-lg') do %>
        &nbsp;<%= "Reactivate ReEntrant" %>
      <% end %>
    <% end %>
  <%end%>







</div>