config/routes.rb
Rails.application.routes.draw do
  
  # Semi-static page routes
  get 'home', to: 'home#index', as: :index
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search
  get 'home/filter', to: 'home#filter', as: :filter
  root 'home#index'


  # Authentication and users
  resources :sessions
  resources :users
  get 're_entrants/new', to: 're_entrants#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

 # Special routes
  get 'resources/:id/share/', to: 'transactions#new', as: :share_resource_path
  get 'resources/:id/confirm', to: 'transactions#confirm', as: :confirm_resource_path
  get 'resources/:id/use_resource', to: 'transactions#use_resource', as: :use_resource_path
  get 'resources/:id/deactivate_resource', to: 'resources#deactivate', as: :deactivate_resource_path
  get 'resources/:id/reactivate_resource', to: 'resources#reactivate', as: :reactivate_resource_path
  get 're_entrants/:id/deactivate', to: 're_entrants#deactivate', as: :deactivate_reentrant_path
  get 're_entrants/:id/reactivate', to: 're_entrants#reactivate', as: :reactivate_reentrant_path
  get 'outreach_workers/:id/deactivate', to: 'outreach_workers#deactivate', as: :deactivate_sow_path
  get 'outreach_workers/:id/reactivate', to: 'outreach_workers#reactivate', as: :reactivate_sow_path

  # Additional Quality-of-life routes
  get 'user/referrals', to: 'users#referrals', as: :get_referral_path
  get 're_entrants/referrals', to: 're_entrants#referrals', as: :get_reentrant_referral_path

  get 'outreach_workers/referred_users', to: 'outreach_workers#referred', as: :get_referred_users_path
  get 'outreach_workers/referrals', to: 'outreach_workers#referrals', as: :get_sow_referral_path


  # Default routes
  resources :outreach_workers
  resources :re_entrants
  resources :flags
  resources :resources
  resources :tags
  resources :transactions

  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_footer.html.erb
<footer class="footer footer-default">
    <div class="container">
      <nav class="float-left">
        <ul>
          <li>
          </li>
          <li>
            
          </li>
        </ul>
      </nav>
    </div>
  </footer>

app/views/partials/_form2_structure.html.erb
<div class="row">
  <div class="col s9">
    <div class="card">    
      <div class="card-content">
        <span class="card-title"><%= type_of_form %></span>
        <%= simple_form_for(object) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%= render partial: "#{fields1}", locals: { f: f } %>
            </div>
          </div>
      </div>
    </div>

    <div class="row">
      <div class="col s12">
        <div class="card grey lighten-3">
          <div class="row">
            <div class="card-content">
              <span class="card-title"><%= section_2 %></span>
              <div class="form-inputs">
                <%= render partial: "#{fields2}", locals: { f: f } %>
              </div>
            </div>
          </div>    
        </div>              
      </div>
    </div>

      <div class="row">
        <div class="form-actions col s9">
          <%= f.button :submit %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= link_to 'Back', :back %>

app/views/partials/_nav_admin.html.erb
   <nav class="navbar bg-primary fixed-top navbar-expand-lg" color-on-scroll="100" id="sectionsNav">
  <div class="container">
    <div class="navbar-translate">

    <a class="navbar-brand" href="/">NewERA412</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="sr-only">Toggle navigation</span>
    <span class="navbar-toggler-icon"></span>
    <span class="navbar-toggler-icon"></span>
    <span class="navbar-toggler-icon"></span>
    </button>
  </div>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="<%=resources_path%>">Resources <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=re_entrants_path%>">Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=outreach_workers_path%>">Outreach Workers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=transactions_path%>">Referrals</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=tags_path%>">Tags</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=new_resource_path%>">New Resource</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=new_re_entrant_path%>">New User</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="<%=new_outreach_worker_path%>">New Outreach Worker</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="<%=new_tag_path%>">New Tag</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=logout_path%>">Logout</a>
        </li>
       
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_nav_guest.html.erb
 <nav class="navbar bg-primary fixed-top navbar-expand-lg" color-on-scroll="100" id="sectionsNav">
    <div class="container">
      <div class="navbar-translate">
        <a class="navbar-brand" href="/">
          NewERA412 </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="sr-only">Toggle navigation</span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          
          <li class="nav-item active">
            <a class="nav-link" href="<%=index_path%>">
             Home <span class="sr-only">(current)</span></a>
        </li>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="<%=login_path%>">
             Log In
            </a>
          </li>
         
        </ul>
      </div>
    </div>
  </nav>

app/views/partials/_nav_reentrant.html.erb
  <nav class="navbar bg-primary fixed-top navbar-expand-lg" color-on-scroll="100" id="sectionsNav">
  <div class="container">
    <div class="navbar-translate">

    <a class="navbar-brand" href="/">NewERA412</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="sr-only">Toggle navigation</span>
    <span class="navbar-toggler-icon"></span>
    <span class="navbar-toggler-icon"></span>
    <span class="navbar-toggler-icon"></span>
    </button>
  </div>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="<%=resources_path%>">Resources <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=re_entrant_path(ReEntrant.find_by_user_id(current_user.id))%>">My Account</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=get_reentrant_referral_path_url%>">My Resources</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=index_path%>">About Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=logout_path%>">Logout</a>
        </li>
       
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_nav_sow.html.erb
  <nav class="navbar bg-primary fixed-top navbar-expand-lg" color-on-scroll="100" id="sectionsNav">
  <div class="container">
    <div class="navbar-translate">

    <a class="navbar-brand" href="/">NewERA412</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="sr-only">Toggle navigation</span>
    <span class="navbar-toggler-icon"></span>
    <span class="navbar-toggler-icon"></span>
    <span class="navbar-toggler-icon"></span>
    </button>
  </div>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="<%=resources_path%>">Resources</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=outreach_worker_path(OutreachWorker.find_by_user_id(current_user.id))%>">My Account</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=get_sow_referral_path_url%>">My Referrals</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=signup_path%>">Create an Account</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=index_path%>">Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="<%=logout_path%>">Logout</a>
        </li>
       
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_share.html.erb
<!-- <div class="row valign-wrapper" id="topbar">
  <div class="col s1">
    LOGO
  </div>
  
  </div>
</div>
 -->

<!-- Modal Trigger -->
    <tr>
      <td><%=link_to resource.name, resource_path(resource)%></td>
      <td><%=resource.phone%></td>
      <td><%=resource.email%></td>
      <td><%=resource.address%></td>
      <td><%=resource.name%></td>
      <td class="waves-effect waves-light btn modal-trigger" href="#modal<%=resource.name%>"><%=link_to "Share", share_resource_path_url(resource)%> 
      </td>
    </tr>

  <!-- Modal Structure -->
 