config/routes.rb
Rails.application.routes.draw do
  
  # Semi-static page routes
  get 'home', to: 'home#index', as: :index
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search
  get 'home/filter', to: 'home#filter', as: :filter
  root 'home#index'


  # Authentication and users
  resources :sessions
  resources :users
  get 're_entrants/new', to: 're_entrants#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

 # Special routes
  get 'resources/:id/share/', to: 'transactions#new', as: :share_resource_path
  get 'resources/:id/confirm', to: 'transactions#confirm', as: :confirm_resource_path
  get 'resources/:id/use_resource', to: 'transactions#use_resource', as: :use_resource_path
  get 'resources/:id/deactivate_resource', to: 'resources#deactivate', as: :deactivate_resource_path
  get 'resources/:id/reactivate_resource', to: 'resources#reactivate', as: :reactivate_resource_path
  get 're_entrants/:id/deactivate', to: 're_entrants#deactivate', as: :deactivate_reentrant_path
  get 're_entrants/:id/reactivate', to: 're_entrants#reactivate', as: :reactivate_reentrant_path
  get 'outreach_workers/:id/deactivate', to: 'outreach_workers#deactivate', as: :deactivate_sow_path
  get 'outreach_workers/:id/reactivate', to: 'outreach_workers#reactivate', as: :reactivate_sow_path

  # Additional Quality-of-life routes
  get 'user/referrals', to: 'users#referrals', as: :get_referral_path
  get 're_entrants/referrals', to: 're_entrants#referrals', as: :get_reentrant_referral_path

  get 'outreach_workers/referred_users', to: 'outreach_workers#referred', as: :get_referred_users_path
  get 'outreach_workers/referrals', to: 'outreach_workers#referrals', as: :get_sow_referral_path


  # Default routes
  resources :outreach_workers
  resources :re_entrants
  resources :flags
  resources :resources
  resources :tags
  resources :transactions

  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/outreach_worker.rb
class OutreachWorker < ApplicationRecord
  belongs_to :user
  has_many :transactions
  has_many :re_entrants, through: :transactions

  scope :active,       -> { where(active: true) }
  scope :alphabetical, -> {includes(:user).order('users.first_name, users.last_name')}

  # delegates
  delegate :email, to: :user, allow_nil: true
  delegate :phone, to: :user, allow_nil: true
  delegate :first_name, to: :user, allow_nil: true
  delegate :last_name, to: :user, allow_nil: true


end

app/controllers/outreach_workers_controller.rb
class OutreachWorkersController < ApplicationController
  before_action :set_outreach_worker, only: [:show, :edit, :update, :destroy, :deactivate, :reactivate]

  # GET /outreach_workers
  # GET /outreach_workers.json
  def index
    @outreach_workers = OutreachWorker.alphabetical.paginate(:page => params[:page]).per_page(20)
  end

  # GET /outreach_workers/1
  # GET /outreach_workers/1.json
  def show
    @transactions = @outreach_worker.transactions.paginate(:page => params[:page]).per_page(10)
  end

  # GET /outreach_workers/new
  def new
    @outreach_worker = OutreachWorker.new
  end

  # GET /outreach_workers/1/edit
  def edit
  end

  # POST /outreach_workers
  # POST /outreach_workers.json
  def create
    @user = User.new(user_params)
    @user.role = "sow"
    @outreach_worker = OutreachWorker.new
    @outreach_worker.organization = params[:outreach_worker][:organization]
    

    respond_to do |format|
      if @user.save
        @outreach_worker.user_id = @user.id
        if @outreach_worker.save
          logger.info("Saving is good!")
          format.html { redirect_to @outreach_worker, notice: 'Outreach Worker was successfully created.' }
          format.json { render :show, status: :created, location: @outreach_worker }
        else
          format.html { render :index }
          format.json { render json: @outreach_worker.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :show }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outreach_workers/1
  # PATCH/PUT /outreach_workers/1.json
  def update
    respond_to do |format|
      if @outreach_worker.update(outreach_worker_params)
        format.html { redirect_to @outreach_worker, notice: 'Outreach worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @outreach_worker }
      else
        format.html { render :edit }
        format.json { render json: @outreach_worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /outreach_workers/referred_users
  def referred
    @users = ReEntrant.for_sow(current_user.outreachWorker.id)
  end

  # GET /outreach_workers/referrals
  def referrals
    @transactions = Transaction.for_outreach_worker(current_user.outreachWorker.id).by_recent.paginate(:page => params[:page]).per_page(10)
  end

  # DELETE /outreach_workers/1
  # DELETE /outreach_workers/1.json
  def destroy
    @outreach_worker.destroy
    respond_to do |format|
      format.html { redirect_to outreach_workers_url, notice: 'Outreach worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

   def deactivate
    respond_to do |format|
      @outreach_worker.update(active: false)
      format.html { redirect_to outreach_workers_url, notice: 'Street Outreach Worker was successfully deactivated.' }
      format.json { head :no_content }
    end

  end

  def reactivate
    respond_to do |format|
      @outreach_worker.update(active: true)
      format.html { redirect_to @outreach_worker, notice: 'Street Outreach Worker was successfully reactivated.' }
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outreach_worker
      @outreach_worker = OutreachWorker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outreach_worker_params
      params.require(:outreach_worker).permit(:first_name, :last_name, :active, :email, :phone, :username, :password, :password_confirmation, :organization, :user_id)
    end

    def user_params
      params.require(:outreach_worker).permit(:first_name, :last_name, :active, :email, :phone, :username, :password, :password_confirmation)
    end
end

app/helpers/outreach_workers_helper.rb
module OutreachWorkersHelper
end

app/views/outreach_workers/_form.html.erb
<%= form_with(model: outreach_worker, local: true) do |form| %>
  <% if outreach_worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(outreach_worker.errors.count, "error") %> prohibited this outreach_worker from being saved:</h2>

      <ul>
      <% outreach_worker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

   <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>

   <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :organization %>
    <%= form.text_field :organization, class: "form-control" %>
  </div>

  

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

 

 

  <div class="actions">
    <%= form.submit "Create Outreach Worker", class: "btn btn-primary btn-raised btn-lg" %>
  </div>
<% end %>

app/views/outreach_workers/_sow_fields.html.erb
 <%= f.input :organization, label_html: { class: 'active' }, include: true%> 
 

app/views/outreach_workers/_user_fields.html.erb
<%= f.input :email, label_html: { class: 'active' } %>
<%= f.input :phone, label_html: { class: 'active' } %>
<%= f.input :password, label_html: { class: 'active' } %>
<%= f.input :password_confirmation, label_html: { class: 'active' } %>
<%= f.input :first_name, label_html: { class: 'active' } %>
<%= f.input :last_name, label_html: { class: 'active' } %>

app/views/outreach_workers/edit.html.erb
<h1>Editing Outreach Worker</h1>

<%= render 'form', outreach_worker: @outreach_worker %>

<%= link_to 'Show', @outreach_worker %> |
<%= link_to 'Back', outreach_workers_path %>

app/views/outreach_workers/index.html.erb
<div class="container">

<p id="notice"><%= notice %></p>



<h2>Outreach Workers</h2>

<% if current_user.role?(:admin) %>
  <%= link_to 'New Outreach Worker', new_outreach_worker_path %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name </th>
      <th>Organization</th>
      <th>Phone</th>
      <th>Email</th>
      <% if current_user.role?(:admin) %>
      <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @outreach_workers.each do |outreach_worker| %>
      <tr>
        <td><%= link_to outreach_worker.user.name, outreach_worker %></td>
        <td><%= outreach_worker.organization %></td>
        <td><%= outreach_worker.user.phone %></td>
        <td><%= outreach_worker.user.email %></td>
        <% if current_user.role?(:admin) %>
        <td><%= link_to 'Edit', edit_outreach_worker_path(outreach_worker) %> </td>
        <td><%= link_to 'Delete', outreach_worker, method: :delete, data: { confirm: 'Are you sure?' } %> </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



</div>

app/views/outreach_workers/new.html.erb
<div class="container">

<h3>Create a New Outreach Worker</h3>


<%= render 'form', outreach_worker: @outreach_worker %>

</div>

app/views/outreach_workers/referrals.html.erb
<div class="container">

<h4>Your Referrals</h4>

<% if @transactions.empty? %>
  <h4>You have not referred any resources yet.</h4>
<% else %>

    <% @transactions.each do |referral| %>
    <div class="card" style="width: 20rem;">
      <div class="card-body">
        <h4 class="card-title"><%=link_to referral.resource.name, resource_path(referral.resource)%></h4>
        <h6 class="card-subtitle mb-2 text-muted">Referred to <%= link_to referral.re_entrant.user.name, re_entrant_path(referral.re_entrant) %></h6>
        <p class="card-text">
          <% if referral.resource_accessed %>
            This resource was accessed at <%=referral.dateAccessed%>
          <% else %>
            This resource has not been accessed yet.
          <% end %>
         </p>
        
      </div>
    </div>
  <% end %>
<% end %>

</div>

app/views/outreach_workers/referred.html.erb
<h4>Referred Users</h4>

<% if @users.empty? %>
  <h4>You have not referred any users yet.</h4>
<% else %>

    <% @users.each do |referral| %>
    <div class="card" style="width: 20rem;">
      <div class="card-body">
        <h4 class="card-title"><%=link_to referral.name, re_entrant_path(referral.reentrant)%></h4>
        
      </div>
    </div>
  <% end %>
<% end %>

app/views/outreach_workers/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<h2>
<%= @outreach_worker.user.name %>
</h2>

<% if not @outreach_worker.active %>
  <p>This user is inactive</p>
  <% end %>

<h4>Account Information</h4>

<p>
  <strong>Email:</strong>
  <%= @outreach_worker.email %>
</p>
<p>
  <strong>Phone Number:</strong>
  <%= @outreach_worker.phone %>
</p>
<p>
  <strong>Organization:</strong>
  <% if @outreach_worker.organization.blank? %>
    N/A
  <% else %>
  <%= @outreach_worker.organization %>
  <% end %>
</p>

<% if @outreach_worker.user == current_user %> 
<%= link_to 'Edit Your Account', edit_outreach_worker_path(@outreach_worker) %>
<% end %>


<%if current_user.role?(:admin) %>
    <% if @outreach_worker.active %>
      <%= link_to(deactivate_sow_path_url, class: 'btn btn-primary btn-raised btn-lg') do %>
        &nbsp;<%= "Deactivate Street Outreach Worker" %>
      <% end %>
     <% else %>
       <%= link_to(reactivate_sow_path_url, class: 'btn btn-primary btn-raised btn-lg') do %>
        &nbsp;<%= "Reactivate Street Outreach Worker" %>
      <% end %>
    <% end %>
  <%end%>





</div>