config/routes.rb
Rails.application.routes.draw do
  
  # Semi-static page routes
  get 'home', to: 'home#index', as: :index
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search
  get 'home/filter', to: 'home#filter', as: :filter
  root 'home#index'


  # Authentication and users
  resources :sessions
  resources :users
  get 're_entrants/new', to: 're_entrants#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

 # Special routes
  get 'resources/:id/share/', to: 'transactions#new', as: :share_resource_path
  get 'resources/:id/confirm', to: 'transactions#confirm', as: :confirm_resource_path
  get 'resources/:id/use_resource', to: 'transactions#use_resource', as: :use_resource_path
  get 'resources/:id/deactivate_resource', to: 'resources#deactivate', as: :deactivate_resource_path
  get 'resources/:id/reactivate_resource', to: 'resources#reactivate', as: :reactivate_resource_path
  get 're_entrants/:id/deactivate', to: 're_entrants#deactivate', as: :deactivate_reentrant_path
  get 're_entrants/:id/reactivate', to: 're_entrants#reactivate', as: :reactivate_reentrant_path
  get 'outreach_workers/:id/deactivate', to: 'outreach_workers#deactivate', as: :deactivate_sow_path
  get 'outreach_workers/:id/reactivate', to: 'outreach_workers#reactivate', as: :reactivate_sow_path

  # Additional Quality-of-life routes
  get 'user/referrals', to: 'users#referrals', as: :get_referral_path
  get 're_entrants/referrals', to: 're_entrants#referrals', as: :get_reentrant_referral_path

  get 'outreach_workers/referred_users', to: 'outreach_workers#referred', as: :get_referred_users_path
  get 'outreach_workers/referrals', to: 'outreach_workers#referrals', as: :get_sow_referral_path


  # Default routes
  resources :outreach_workers
  resources :re_entrants
  resources :flags
  resources :resources
  resources :tags
  resources :transactions

  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/resource.rb
class Resource < ApplicationRecord
    #relationships
    has_many :taggings
    has_many :tags, through: :taggings
    has_many :flaggings
    has_many :flags, through: :flaggings
    STATES_LIST = [['Alabama', 'AL'],['Alaska', 'AK'],['Arizona', 'AZ'],['Arkansas', 'AR'],['California', 'CA'],['Colorado', 'CO'],['Connectict', 'CT'],['Delaware', 'DE'],['District of Columbia ', 'DC'],['Florida', 'FL'],['Georgia', 'GA'],['Hawaii', 'HI'],['Idaho', 'ID'],['Illinois', 'IL'],['Indiana', 'IN'],['Iowa', 'IA'],['Kansas', 'KS'],['Kentucky', 'KY'],['Louisiana', 'LA'],['Maine', 'ME'],['Maryland', 'MD'],['Massachusetts', 'MA'],['Michigan', 'MI'],['Minnesota', 'MN'],['Mississippi', 'MS'],['Missouri', 'MO'],['Montana', 'MT'],['Nebraska', 'NE'],['Nevada', 'NV'],['New Hampshire', 'NH'],['New Jersey', 'NJ'],['New Mexico', 'NM'],['New York', 'NY'],['North Carolina','NC'],['North Dakota', 'ND'],['Ohio', 'OH'],['Oklahoma', 'OK'],['Oregon', 'OR'],['Pennsylvania', 'PA'],['Rhode Island', 'RI'],['South Carolina', 'SC'],['South Dakota', 'SD'],['Tennessee', 'TN'],['Texas', 'TX'],['Utah', 'UT'],['Vermont', 'VT'],['Virginia', 'VA'],['Washington', 'WA'],['West Virginia', 'WV'],['Wisconsin ', 'WI'],['Wyoming', 'WY']]


    validates :name, presence: true, uniqueness: { case_sensitive: false }
    validates :street_1, presence: true
    validates :city, presence: true
    validates :state, presence: true
    validates :zip, presence: true
    validates :state, inclusion: { in: STATES_LIST.map{|a,b| b}, message: "is not valid state", allow_blank: true }
    validates :zip, format: { with: /\A\d{5}\z/, message: "should be five digits long", allow_blank: true }
    validates_format_of :email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil))\z/i, message: "is not a valid format", allow_blank: true
    validates_format_of :phone, with: /\A\(?\d{3}\)?[-. ]?\d{3}[-.]?\d{4}\z/, message: "should be 10 digits (area code needed) and delimited with dashes or dots"

    scope :alphabetical, -> { order('name') }
    scope :active,       -> { where(active: true) }
    # pg_search_scope :quick_search, against: [:name, :desc], associated_against: {tags: [:name]}

    def self.search(search)
        Resource.where("lower(resources.desc) LIKE :search OR lower(resources.name) LIKE :search", search: "%#{search.downcase}%" )
    end

    #implement realistic reentry caterogies from website, let admin add new categories

    def self.tagged_with(name)
        Tag.find_by!(name: name).resources
    end

    def address
        street_1 + "\n" + city + ", " + state + ", " + zip
    end

    def referred?(reentrant)
        not Transaction.where("transactions.resource_id = ? AND transactions.re_entrant_id = ? AND transactions.resource_accessed = ?", self.id, reentrant.id, false).empty?
    end
end

app/views/resources/_filter.html.erb
<div id="filter">
  <%= form_tag(resources_path, method: :get) do %>
    <%= collection_select :resource, :tagged_with, Tag.all, :name, :name, prompt: true %>
    <%= submit_tag("Filter") %>
  <% end %>
</div>

app/views/resources/_form.html.erb
<%= form_with(model: resource, local: true) do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>
      <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :street_1 %>
    <%= form.text_field :street_1, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :street_2 %>
    <%= form.text_field :street_2, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :webpage %>
    <%= form.text_field :webpage, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :tag_ids %>
    <br/>
    <% if Tag.all.empty?%>
    <p>No Tags to Display</p>
    <% else %>
    <% for tag in Tag.all %>
      <%= check_box_tag "resource[tag_ids][]", tag.id%>
      <%= tag.name %>
    <br/>
    <% end %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit "Create Resource", class: "btn btn-primary btn-raised btn-lg" %>
  </div>
<% end %>

app/views/resources/_search.html.erb
<div id="search">

<%= form_tag(resources_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag("Search") %>
<% end %>

</div>

app/views/resources/edit.html.erb
<div class="container">

	<h2>Editing Resource</h2>

	<%= render 'form', resource: @resource %>

	<%= link_to 'Show', @resource %> |
	<%= link_to 'Back', resources_path %>

</div>

app/views/resources/index.html.erb
<div class="container">

<!-- <p id="notice"><%= notice %></p> -->

  <%= render 'search' %>
  <%= render 'filter' %>


  <h4>Resources</h4>
  <p>We provide a variety of employment and educational resources. Filter through our categories to secure the right resource for you.</p>

  <% if current_user.role?(:admin) %>
    <%= link_to 'New Resource', new_resource_path %>
  <% end %>
  
  <% @resources.alphabetical.each do |resource| %>
    <div class="card" style="width: 20rem;">
      <div class="card-body">
        <h4 class="card-title"><%=link_to resource.name, resource_path(resource)%></h4>
        <h6 class="card-subtitle mb-2 text-muted">

         <!--WARREN: ADD NAMES OF EACH TAG IN THIS SUBTITLE TEXT -->


            


          </h6>
        <p class="card-text"><%= truncate(resource.desc, :length => 150, :separator => ' ') %> </p>
        <% if current_user.role?(:reentrant) %>
          <a href="<%= resource.webpage %>" class="card-link">Visit Website</a>
          <a href="<%=resource_path(resource)%>" class="card-link">View Resource</a>
        <% else %>
          <a href="<%=resource_path(resource)%>" class="card-link">View Resource</a>
          <a href="<%=share_resource_path_url(resource)%>" class="card-link">Share</a>

        <% end %>
      </div>
    </div>
  <% end %>

  <br>

  

</div>

app/views/resources/new.html.erb
<div class="container">

<h3>Create a New Resource</h3>

<%= render 'form', resource: @resource %>

<%= link_to 'Back', resources_path %>

</div>

app/views/resources/show.html.erb
<div class="container">

	<p id="notice"><%= notice %></p>

	<h2><%= @resource.name %></h2>
	<% if not @resource.active %>
	<p>This resource is inactive</p>
	<% end %>
	<hr>

	<!-- <img src="<%= @resource.image %>"> -->

	  <p><b>Phone</b>: <%= @resource.phone %></p>
	  
	  <% if @resource.email.blank? %>

	  <% else %>
	  	<p><b>Email</b>: <%= @resource.email %></p>
	  	<% end %>
	  <p><b>Address</b>: <%= @resource.address %></p>


<% if @tags.empty? %>
<% else %>

<table>
  <thead>
    <tr>
      <th>Tags</th>
    </tr>
  </thead>

	<tbody>
    	<% @tags.each do |tag_obj| %>
      	<tr>
        	<td><%= link_to tag_obj.tag.name, tag_path(tag_obj.tag) %></td>
      	</tr>
    	<% end %>
  	</tbody>

</table>

<% end %>

<br>

	<p><%= @resource.desc %></p>

	
	<%if @referred %>
    <p><a href="<%= use_resource_path_url %>" class="btn btn-primary btn-raised btn-lg">Verify Resource Used</a></p>
  <%end%>

  <p><a href="<%= @resource.webpage %>" class="btn btn-primary btn-raised btn-lg">Visit Website</a>
  	<%if current_user.role?(:sow) %>
		<a href="<%=share_resource_path_url(@resource)%>" class="btn btn-primary btn-raised btn-lg">Share</a>
  	<%end%>
  </p>

  
	<%if current_user.role?(:admin) %>
		<a href="<%= edit_resource_path(@resource) %>" class="btn btn-primary btn-raised btn-lg">Edit</a>
		<% if @resource.active %>
	  	<%= link_to(deactivate_resource_path_url, class: 'btn btn-primary btn-raised btn-lg') do %>
	  		&nbsp;<%= "Deactivate Resource" %>
	    <% end %>
	   <% else %>
	     <%= link_to(reactivate_resource_path_url, class: 'btn btn-primary btn-raised btn-lg') do %>
  		  &nbsp;<%= "Reactivate Resource" %>
      <% end %>
    <% end %>
  <%end%>
  <br>
  <br>
   <a href="<%= resources_path %>" class="btn btn-primary btn-raised btn-lg">Back</a>
</div>